language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt -jvm-opts travis/jvmopts.compile debian:packageBin
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
  - $HOME/.sbt

addons:
  apt:
    packages:
    - dpkg-deb
    - dpkg-sig
    - dpkg-genchanges
    - lintian
    - fakeroot

after_success:
  "curl -F package=target/testTravisBuild_1.0_amd64.deb https://iyNkjR2UTrKHmbZPzPxB@push.fury.io/lembrd/"
